{
  FrameLayout;
  id="home_view";
  layout_height="fill";
  layout_width="fill";
  background="#FF73AA95";
  {
    PageView;
    id="page";
    layout_height="fill";
    layout_width="fill";
    OverScrollMode=2;
    pages={
      "page/page1",
      "page/page2",
    }
  },
  {
    FrameLayout;
    id="bottom_bar";
    layout_height="70dp";
    layout_width="fill";
    elevation="9";
    layout_gravity="bottom";
    {
      CardView;
      layout_height=activity.getHeight();
      layout_width=activity.getHeight();
      layout_gravity="center|top";
      radius=activity.getHeight()/2;
      elevation="10";
      CardBackgroundColor="#FF73AA95";
    },
    {
      LinearLayout;
      layout_height="fill";
      layout_width="fill";
      elevation="11";
      orientation="horizontal";
      {
        FrameLayout;
        layout_height="fill";
        layout_width="fill";
        layout_weight="1";
      },
      {
        FrameLayout;
        layout_height="fill";
        layout_width="fill";
        layout_weight="1";
        onClick=function(v)
          水珠动画(v,500)
        end,
        {
          ImageView;
          layout_height="25dp";
          layout_width="25dp";
          layout_gravity="center";
          src="image/home.png";
        },
        {
          ImageView;
          id="bottom_bar_one";
          layout_height="25dp";
          layout_width="25dp";
          layout_marginLeft="2.5dp";
          layout_marginTop="1dp";
          layout_gravity="center";
          colorFilter="#FFFFCD36";
          src="image/home2.png";
        }
      },
      {
        FrameLayout;
        layout_height="fill";
        layout_width="fill";
        layout_weight="1";
        {
          CardView;
          layout_height="50dp";
          layout_width="50dp";
          layout_gravity="center";
          radius="25dp";
          elevation="0";
          CardBackgroundColor="#ffffffff";
          onClick=function(v)
            旋转动画(ftb,{0,135},300)
            旋转动画(ftb2,{0,135},300)
            view=home_view
            view.destroyDrawingCache();
            view.setDrawingCacheEnabled(true);
            view.buildDrawingCache();
            bmp = view.getDrawingCache();
            tan_chuang.addView(loadlayout({
              ImageView;
              layout_height="fill";
              layout_width="fill";
              scaleType="fitXY";
              ImageBitmap=高斯模糊(activity,缩略图片(bmp,50),1,2);
              onClick=function(v)
                旋转动画(ftb,{135,0},300)
                旋转动画(ftb2,{135,0},300)
                animator = ViewAnimationUtils.createCircularReveal(tan_chuang,activity.getWidth()/2,activity.getHeight(),Math.hypot(tan_chuang.getWidth(),tan_chuang.getHeight()),0);
                animator.setInterpolator(AccelerateInterpolator());
                animator.setDuration(800);
                animator.start()
                task(790,function()
                  tan_chuang.removeView(v)
                  tan_chuang.setVisibility(View.INVISIBLE)
                end)
              end,
            }),0)
            tan_chuang.setVisibility(View.VISIBLE)
            animator = ViewAnimationUtils.createCircularReveal(tan_chuang,activity.getWidth()/2,activity.getHeight(),0,Math.hypot(tan_chuang.getWidth(),tan_chuang.getHeight()));
            animator.setInterpolator(AccelerateInterpolator());
            animator.setDuration(800);
            animator.start()
            纵振动画(ftb_one,"Y",{0,-30,0,30,0},400)
            纵振动画(ftb_two,"Y",{0,-30,0,30,0},450)
            纵振动画(ftb_three,"Y",{0,-30,0,30,0},500)
            纵振动画(ftb_four,"Y",{0,-30,0,30,0},550)
            纵振动画(ftb_five,"Y",{0,-30,0,30,0},600)
            纵振动画(ftb_six,"Y",{0,-30,0,30,0},750)
            纵振动画(ftb_seven,"Y",{0,-30,0,30,0},800)
            纵振动画(ftb_eight,"Y",{0,-30,0,30,0},850)
          end,
          {
            ImageView;
            id="ftb";
            layout_height="20dp";
            layout_width="20dp";
            layout_gravity="center";
            colorFilter="#FF73AA95";
            src="image/plus.png";
          }
        }
      },
      {
        FrameLayout;
        layout_height="fill";
        layout_width="fill";
        layout_weight="1";
        onClick=function(v)
          水珠动画(v,500)
        end,
        {
          ImageView;
          layout_height="25dp";
          layout_width="25dp";
          layout_gravity="center";
          src="image/custom.png";
          id="kaki";
        },
        {
          ImageView;
          id="bottom_bar_two";
          layout_height="23dp";
          layout_width="23dp";
          layout_marginLeft="0dp";
          layout_marginTop="1dp";
          layout_gravity="center";
          colorFilter="#FFFFCD36";
          src="image/custom2.png";
        }
      },
      {
        FrameLayout;
        layout_height="fill";
        layout_width="fill";
        layout_weight="1";
      }
    }
  },
  {
    FrameLayout;
    id="tan_chuang";
    Visibility="invisible";
    layout_height="fill";
    layout_width="fill";
    elevation="20";
    background="#88ffffff";
    {
      LinearLayout;
      layout_height="wrap";
      layout_width="fill";
      layout_gravity="bottom";
      layout_marginBottom="150dp";
      orientation="vertical";
      {
        LinearLayout;
        layout_height="wrap";
        layout_width="fill";
        elevation="25";
        orientation="horizontal";
        {
          LinearLayout;
          id="ftb_one";
          layout_height="wrap";
          layout_width="fill";
          layout_weight="1";
          orientation="vertical";
          {
            FrameLayout;
            layout_height="25%w";
            layout_width="fill";
            {
              CardView;
              layout_height="13%w";
              layout_width="13%w";
              layout_gravity="center";
              radius="6.5%w";
              elevation="0";
              CardBackgroundColor="#FF4CB050";
              {
                ImageView;
                layout_height="20dp";
                layout_width="20dp";
                layout_gravity="center";
                colorFilter="#ffffffff";
                background="image/tanchuang/search.png";
              }
            }
          },
          {
            TextView;
            text="TrurCaller MOD";
            textSize="12dp";
            textColor="#FF232323";
            layout_height="40dp";
            layout_width="fill";
            layout_marginTop="-20dp";
            gravity="center";
          }
        },
        {
          LinearLayout;
          id="ftb_two";
          layout_height="wrap";
          layout_width="fill";
          layout_weight="1";
          orientation="vertical";
          {
            FrameLayout;
            layout_height="25%w";
            layout_width="fill";
            {
              CardView;
              layout_height="13%w";
              layout_width="13%w";
              layout_gravity="center";
              radius="6.5%w";
              elevation="0";
              CardBackgroundColor="#FFFF9700";
              {
                ImageView;
                layout_height="20dp";
                layout_width="20dp";
                layout_gravity="center";
                colorFilter="#ffffffff";
                background="image/tanchuang/collect.png";
              }
            }
          },
          {
            TextView;
            text="Canva MOD";
            textSize="12dp";
            textColor="#FF232323";
            layout_height="40dp";
            layout_width="fill";
            layout_marginTop="-20dp";
            gravity="center";
          }
        },
        {
          LinearLayout;
          id="ftb_three";
          layout_height="wrap";
          layout_width="fill";
          layout_weight="1";
          orientation="vertical";
          {
            FrameLayout;
            layout_height="25%w";
            layout_width="fill";
            {
              CardView;
              layout_height="13%w";
              layout_width="13%w";
              layout_gravity="center";
              radius="6.5%w";
              elevation="0";
              CardBackgroundColor="#FFF44236";
              {
                ImageView;
                layout_height="20dp";
                layout_width="20dp";
                layout_gravity="center";
                colorFilter="#ffffffff";
                background="image/tanchuang/history.png";
              }
            }
          },
          {
            TextView;
            text="Kinemaster MOD";
            textSize="12dp";
            textColor="#FF232323";
            layout_height="40dp";
            layout_width="fill";
            layout_marginTop="-20dp";
            gravity="center";
          }
        },
        {
          LinearLayout;
          id="ftb_four";
          layout_height="wrap";
          layout_width="fill";
          layout_weight="1";
          orientation="vertical";
          {
            FrameLayout;
            layout_height="25%w";
            layout_width="fill";
            {
              CardView;
              layout_height="13%w";
              layout_width="13%w";
              layout_gravity="center";
              radius="6.5%w";
              elevation="0";
              CardBackgroundColor="#FFF26DDA";
              {
                ImageView;
                layout_height="20dp";
                layout_width="20dp";
                layout_gravity="center";
                colorFilter="#ffffffff";
                background="image/tanchuang/sys.png";
              }
            }
          },
          {
            TextView;
            text="TurboVpn MOD";
            textSize="12dp";
            textColor="#FF232323";
            layout_height="40dp";
            layout_width="fill";
            layout_marginTop="-20dp";
            gravity="center";
          }
        }
      },
      --[[ {
        LinearLayout;
        layout_height="wrap";
        layout_width="fill";
        orientation="horizontal";
        {
          LinearLayout;
          id="ftb_five";
          layout_height="wrap";
          layout_width="fill";
          layout_weight="1";
          orientation="vertical";
          {
            FrameLayout;
            layout_height="25%w";
            layout_width="fill";
            {
              CardView;
              layout_height="13%w";
              layout_width="13%w";
              layout_gravity="center";
              radius="6.5%w";
              elevation="0";
              CardBackgroundColor="#FFE61E5F";
              {
                ImageView;
                layout_height="20dp";
                layout_width="20dp";
                layout_gravity="center";
                colorFilter="#ffffffff";
                src="image/tanchuang/share.png";
              }
            }
          },
          {
            TextView;
            text="分享";
            textSize="12dp";
            textColor="#FF232323";
            layout_height="40dp";
            layout_width="fill";
            layout_marginTop="-20dp";
            gravity="center";
          }
        },
        {
          LinearLayout;
          id="ftb_six";
          layout_height="wrap";
          layout_width="fill";
          layout_weight="1";
          orientation="vertical";
          {
            FrameLayout;
            layout_height="25%w";
            layout_width="fill";
            {
              CardView;
              layout_height="13%w";
              layout_width="13%w";
              layout_gravity="center";
              radius="6.5%w";
              elevation="0";
              CardBackgroundColor="#FF00BCD5";
              {
                ImageView;
                layout_height="20dp";
                layout_width="20dp";
                layout_gravity="center";
                colorFilter="#ffffffff";
                src="image/tanchuang/pocket.png";
              }
            }
          },
          {
            TextView;
            text="钱包";
            textSize="12dp";
            textColor="#FF232323";
            layout_height="40dp";
            layout_width="fill";
            layout_marginTop="-20dp";
            gravity="center";
          }
        },
        {
          LinearLayout;
          id="ftb_seven";
          layout_height="wrap";
          layout_width="fill";
          layout_weight="1";
          orientation="vertical";
          {
            FrameLayout;
            layout_height="25%w";
            layout_width="fill";
            {
              CardView;
              layout_height="13%w";
              layout_width="13%w";
              layout_gravity="center";
              radius="6.5%w";
              elevation="0";
              CardBackgroundColor="#FFA671FF";
              {
                ImageView;
                layout_height="20dp";
                layout_width="20dp";
                layout_gravity="center";
                colorFilter="#ffffffff";
                -- src="image/tanchuang/apps.png";
                background="image/tanchuang/apps.png";

              }
            }
          },
          {
            TextView;
            text="综合";
            textSize="12dp";
            textColor="#FF232323";
            layout_height="40dp";
            layout_width="fill";
            layout_marginTop="-20dp";
            gravity="center";
          }
        },
        {
          LinearLayout;
          id="ftb_eight";
          layout_height="wrap";
          layout_width="fill";
          layout_weight="1";
          orientation="vertical";
          {
            FrameLayout;
            layout_height="25%w";
            layout_width="fill";
            {
              CardView;
              layout_height="13%w";
              layout_width="13%w";
              layout_gravity="center";
              radius="6.5%w";
              elevation="0";
              CardBackgroundColor="#FF2196F3";
              {
                ImageView;
                layout_height="22dp";
                layout_width="22dp";
                layout_gravity="center";
                colorFilter="#ffffffff";
                src="image/tanchuang/talk.png";
              }
            }
          },
      {
        TextView;
        text="话题";
        textSize="12dp";
        textColor="#FF232323";
        layout_height="40dp";
        layout_width="fill";
        layout_marginTop="-20dp";
        gravity="center";
      }
    }
  }
},]]--
      {
        FrameLayout;
        layout_height="70dp";
        layout_width="fill";
        layout_gravity="bottom";
        {
          ImageView;
          id="ftb2";
          layout_height="20dp";
          layout_width="20dp";
          layout_gravity="center";
          colorFilter="#FF73AA95";
          src="image/plus.png";
        }
      }
    },
  }}